version: '3.5'

services:
  api:
    image: darkphoenix777/api
    build: .
    container_name: darkphoenix777/api
    ports:
      - 8000:8000
    restart: on
    environment:
      DEBUG: false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s