version: '3'

services:
  ocr:
    image: ocr
    container_name: ocr
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - my_network
  text_encoder:
    image: bert
    container_name: text_encoder
    ports:
      - 8001:8001
    depends_on:
      - ocr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - my_network
  image_encoder:
    image: clip
    container_name: image_encoder
    ports:
      - 8002:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - my_network
  model:
    image: classifier
    container_name: model
    ports:
      - 8004:8004
    depends_on:
      - ocr
      - text_encoder
      - image_encoder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge