version: '3.5'

services:
  api:
    image: api
    build: .
    container_name: api
    ports:
      - 8000:8000
    environment:
      DEBUG: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]