version: '3.5'

services:
  api:
    image: darkphoenix777/api
    build: .
    container_name: api
    ports:
      - 8000:8000
    restart: on
    environment:
      DEBUG: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s